name: GH-App-Auth
description: Generate an API token for a GitHub App
inputs:
  app_id:
    required: true
    type: string
  installation_id:
    required: true
    type: string
secrets:
  private_key:
    required: true
outputs:
  dummy:
    description: "API token to use when authenticating as your GitHub app"
    value: ${{ steps.dummy.outputs.dummy }}
  token:
    description: "API token to use when authenticating as your GitHub app"
    value: ${{ steps.generate-app-token.outputs.token }}
runs:
  using: "composite"
  steps:
    - run: echo ${{ github.action_path }}
    - run: ls ${{ github.action_path }}
    - id: generate-app-token
      run: echo "::set-output name=token::$(${{ github.action_path }}/bin/appauth-linux)"
      env:
        APP_ID: ${{ inputs.app_id }}
        INSTALLATION_ID: ${{ inputs.installation_id }}
        PRIVATE_KEY: ${{ secrets.private_key }}
    - id: dummy
      run: echo "::set-output name=dummy::dummy"