name: GH-App-Auth
description: Generate an API token for a GitHub App
inputs:
  app_id:
    required: true
    type: string
  installation_id:
    required: true
    type: string
  private_key:
    required: true
    type: string
outputs:
  token:
    description: "API token to use when authenticating as your GitHub app"
    value: ${{ steps.generate-app-token.outputs.token }}
runs:
  using: "composite"
  steps:
    - id: generate-app-token
      run: echo "::set-output name=token::$(${{ github.action_path }}/bin/appauth-linux)"
      env:
        APP_ID: ${{ inputs.app_id }}
        INSTALLATION_ID: ${{ inputs.installation_id }}
        PRIVATE_KEY: ${{ inputs.private_key }}
      shell: bash